Fix optimization in RunFileinfo() causing wrong file status…
PlasticSCM/UE4PlasticPlugin pull request #6
Opened 2022-03-21 16:00 UTC by SRombautsU

… on folders with newly added files (or moved files etc) that is, heterogenous content other than Controlled, Changed, Replaced, Conflicted

The optimization can only be used if all files are optimized out (avoiding the "fileinfo" command entirely)
else we have to keep them all since ParseFileinfoResults() expect the same number of lines of results as there are files listed in the query

So it is a "all or nothing" optimization

2022-03-28 15:57 UTC, danielhompanera requested changes
If I understand it properly, you are now removing the optimization that was there to avoid running fileinfo on files with a status different from the four status lsited on the if in line 996.
If that assuption is right, then I think there is no need for all the code from line 996 to line 1017 as we are always running fileinfo for all the files in AllFiles array.

2022-03-28 16:20 UTC, SRombautsU commented
@danielhompanera 
> If I understand it properly, you are now removing the optimization that was there to avoid running fileinfo on files with a status different from the four status listed on the if in line 996.
No, only partially right: I am not removing the optimization all the time, only if there is a mix of files status (eg a few files with one newly added)

The optimization still apply when:
1. you just check the status of a single file (which is the original use case: "adding a new file shouldn't call fileinfo")
2. you check the status of files that are all new/moved/etc (which is the case when you rename or move a whole folder for instance, or a bunch of assets)

In a summary, I am just disabling the optimization for when we NEED to call fileinfo anyway for other files. I keep the optimization for when it results on no call at all for fileinfo.

it's an "all or nothing" optimization pattern like I mentionned in the Original Post

2022-03-28 16:22 UTC, SRombautsU commented
Let me make a new change to improve the readability, with your comment in mind

2022-03-29 08:38 UTC, danielhompanera approved these changes
Last commit looks very goooood. Thanks!

2022-03-29 08:38 UTC, merged